[[ArgParse]]
deps = ["Compat", "Test", "TextWrap"]
git-tree-sha1 = "295c309124b8385cca4d26b2669b17f9d44d8269"
uuid = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
version = "0.6.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BinDeps]]
deps = ["Compat", "Libdl", "SHA", "URIParser"]
git-tree-sha1 = "160d5d926e83e0970dd549ad9fe0ac3e8107e83c"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "0.8.8"

[[Codecs]]
deps = ["Compat"]
git-tree-sha1 = "511ccd52570f94e45022ef9698146722d4f1f94d"
uuid = "19ecbf4d-ef7c-5e4b-b54a-0a0ff23c5aed"
version = "0.4.0"

[[Compat]]
deps = ["Base64", "Dates", "DelimitedFiles", "Distributed", "InteractiveUtils", "LibGit2", "Libdl", "LinearAlgebra", "Markdown", "Mmap", "Pkg", "Printf", "REPL", "Random", "Serialization", "SharedArrays", "Sockets", "SparseArrays", "Test", "UUIDs", "Unicode"]
git-tree-sha1 = "f3e87ca1e2df8e1e4f82ea504fddf0b9b0894f61"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "0.69.0"

[[Conda]]
deps = ["BinDeps", "Compat", "JSON", "Libdl", "VersionParsing"]
git-tree-sha1 = "6358e179fb9ad0af5ca9cd4d7c691c413cc121f2"
uuid = "8f4d0f93-b110-5947-807f-2305c1781a2d"
version = "0.8.1"

[[DataStructures]]
deps = ["InteractiveUtils", "REPL", "Random", "Serialization", "Test"]
git-tree-sha1 = "ef6f313c82fd80ab75ab3f784353b6c65ebcaacf"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.9.0"

[[Dates]]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[DelimitedFiles]]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[Distributed]]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[InteractiveUtils]]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[JSON]]
deps = ["Dates", "Distributed", "Mmap", "Sockets", "Test", "Unicode"]
git-tree-sha1 = "723a515212612b2175095fa5fa55da0bb4c377e5"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.18.0"

[[LibGit2]]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[MacroTools]]
deps = ["Compat"]
git-tree-sha1 = "18c17737f3d375b86b495144ba7ab359ab3dca57"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.4.2"

[[Markdown]]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[Pkg]]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[[Printf]]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[ProgressMeter]]
deps = ["Compat"]
git-tree-sha1 = "30d3473425cdb13b23ff10dfc7727be8bcc2871a"
uuid = "92933f4c-e287-5a05-a399-4b506db050ca"
version = "0.5.6"

[[PyCall]]
deps = ["Compat", "Conda", "MacroTools", "VersionParsing"]
git-tree-sha1 = "dcb6e67213f812d75100cbf87e9c0fd6aebc01f5"
uuid = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
version = "1.17.1"

[[REPL]]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[Random]]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[SharedArrays]]
uuid = "1a1011a3-84de-559e-8e89-a11a2f7dc383"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[SparseArrays]]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[Test]]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TextWrap]]
deps = ["Compat", "Test"]
git-tree-sha1 = "8355cc559e85469cd4dbe927c375f61d3750e002"
uuid = "b718987f-49a8-5099-9789-dcd902bef87d"
version = "0.3.0"

[[URIParser]]
deps = ["Compat", "Unicode"]
git-tree-sha1 = "0f9c5e2d14e03fbd00696f9394e288bdd5adacbc"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.3.1"

[[UUIDs]]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[VersionParsing]]
deps = ["Compat"]
git-tree-sha1 = "e8524bb636735227fd9d750dfa81f98db8bc5b0c"
uuid = "81def892-9a0e-5fdd-b105-ffc91e053289"
version = "1.1.1"

[[YAML]]
deps = ["Codecs", "Compat"]
git-tree-sha1 = "a81c4f46c19f0eb9abaa90f3112bf536c1cfa7f9"
uuid = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"
version = "0.2.1"
